name       : budgie-backgrounds
version    : '2.0'
release    : 2
source     :
    - https://github.com/BuddiesOfBudgie/budgie-backgrounds/releases/download/v2.0/budgie-backgrounds-v2.0.tar.xz : 429664bb3e2dc46858a53cf853ef88ff49bf77a449fee46bf323cfeeeaeb0dcb
license    : CC0-1.0
component  : desktop.budgie
summary    : Default backgrounds for Budgie
description: |
    Budgie Backgrounds is the default set of background images for the Budgie Desktop.
builddeps  :
    - imagemagick
    - jhead
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
