name       : budgie-backgrounds
version    : '1.0'
release    : 1
source     :
    - https://github.com/BuddiesOfBudgie/budgie-backgrounds/archive/refs/tags/v1.0.tar.gz : 7a8ecd6d395c00c4c15a85ede508236898bc6a8065b039982e89287c6b34e920
license    : CC0-1.0
component  : desktop.budgie
summary    : Default backgrounds for Budgie
description: |
    Budgie Backgrounds is the default set of background images for the Budgie Desktop.
builddeps  :
    - imagemagick
    - jhead
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
